# Generated by Django 4.0.2 on 2022-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_themes_alter_articletheme_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='themes',
        ),
        migrations.AddField(
            model_name='theme',
            name='articles',
            field=models.ManyToManyField(related_name='scopes', through='articles.ArticleTheme', to='articles.Article'),
        ),
    ]
