# Generated by Django 4.0.2 on 2022-02-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_themes_theme_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(related_name='summary', through='articles.ArticleTheme', to='articles.Theme'),
        ),
    ]
