# Generated by Django 4.0.2 on 2022-02-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_theme_articles_article_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='theme',
            name='article',
            field=models.ManyToManyField(related_name='scopes', through='articles.ArticleTheme', to='articles.Article'),
        ),
    ]
