# Generated by Django 4.0.2 on 2022-02-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_themes_theme_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletheme',
            old_name='main',
            new_name='is_main',
        ),
        migrations.AlterField(
            model_name='articletheme',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='articletheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='article',
            field=models.ManyToManyField(related_name='themes', through='articles.ArticleTheme', to='articles.Article'),
        ),
    ]
